module.exports = Object.freeze({
    CHANNEL_IDS: {
        IV100: '259536527221063683',
        IV90: '261331571028656128',
        CP2600: '259296509361782784',
        CP2000: '259505011686375425',
    },
    LENGENDS: [
        "articuno",
        "moltres",
        "zapdos",
        "mewtwo",
        "raikou",
        "entei",
        "suicune",
        "lugia",
        "ho-oh",
        "regirock",
        "regice",
        "registeel",
        "latias",
        "latios",
        "kyogre",
        "groudon",
        "rayquaza",
        "uxie",
        "mesprit",
        "azelf",
        "dialga",
        "palkia",
        "heatran",
        "regigigas",
        "giratina",
        "cresselia",
        "cobalion",
        "terrakion",
        "virizion",
        "tornadus",
        "thundurus",
        "landorus",
        "reshiram",
        "zekrom",
        "kyurem",
        "xerneas",
        "yveltal",
        "tapu koko",
        "tapu lele",
        "tapu bulu",
        "tapu fini",
        "cosmog",
        "cosmoem",
        "solgaleo",
        "lunala",
        "zacian",
        "zamazenta"
    ]
});